### ISSUE TITLE
SetImageFromBytes dont work with tesseract 5.0.0-alpha

### ISSUE THREAD

**Issue by xDWart** [otiai10/gosseract#172]
I have tesseract 5.0.0-alpha and try to set image from bytes. 
It causes the next error:

```
recognizer.test: malloc.c:2385: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.
SIGABRT: abort
PC=0x766e6f24 m=5 sigcode=4294967290

goroutine 0 [idle]:
runtime: unknown pc 0x766e6f24
stack: frame={sp:0x645fd2b8, fp:0x0} stack=[0x63dfe1c4,0x645fddc4)
645fd238:  00000000  00000000  00000000  00000000 
645fd248:  00000000  00000000  00000000  00000000 
645fd258:  00000000  00000000  00000000  00000000 
645fd268:  00000000  00000000  00000000  00000000 
645fd278:  00000000  00000000  00000000  00000000 
645fd288:  00000000  00000000  00000000  00000000 
645fd298:  00000000  00000006  64f00610  00000488 
645fd2a8:  76805000  645fd33c  76f80968  766e6ea8 
645fd2b8: <00000000  00000000  00000000  00000000 
645fd2c8:  00000000  00000000  00000000  00000000 
645fd2d8:  00000000  00000000  00000000  00000000 
645fd2e8:  00000000  00000000  00000000  00000000 
645fd2f8:  00000000  00000000  00000000  00000000 
645fd308:  00000000  00000000  00000000  00000000 
645fd318:  00000000  00000000  00000000  00000000 
645fd328:  00000000  00000000  00000000  00000000 
runtime: unknown pc 0x766e6f24
stack: frame={sp:0x645fd2b8, fp:0x0} stack=[0x63dfe1c4,0x645fddc4)
645fd238:  00000000  00000000  00000000  00000000 
645fd248:  00000000  00000000  00000000  00000000 
645fd258:  00000000  00000000  00000000  00000000 
645fd268:  00000000  00000000  00000000  00000000 
645fd278:  00000000  00000000  00000000  00000000 
645fd288:  00000000  00000000  00000000  00000000 
645fd298:  00000000  00000006  64f00610  00000488 
645fd2a8:  76805000  645fd33c  76f80968  766e6ea8 
645fd2b8: <00000000  00000000  00000000  00000000 
645fd2c8:  00000000  00000000  00000000  00000000 
645fd2d8:  00000000  00000000  00000000  00000000 
645fd2e8:  00000000  00000000  00000000  00000000 
645fd2f8:  00000000  00000000  00000000  00000000 
645fd308:  00000000  00000000  00000000  00000000 
645fd318:  00000000  00000000  00000000  00000000 
645fd328:  00000000  00000000  00000000  00000000 

goroutine 5 [syscall]:
runtime.cgocall(0x141b58, 0x83edd4, 0x800d20)
	/usr/local/go/src/runtime/cgocall.go:128 +0x5c fp=0x83edbc sp=0x83eda4 pc=0x14870
github.com/otiai10/gosseract._Cfunc_CreatePixImageFromBytes(0x888000, 0x247, 0x0)
	_cgo_gotypes.go:137 +0x38 fp=0x83edd0 sp=0x83edbc pc=0x13a278
github.com/otiai10/gosseract.(*Client).SetImageFromBytes(0x83eefc, 0x888000, 0x247, 0x28e, 0xb10080, 0x0)
	/home/pi/go/pkg/mod/github.com/otiai10/gosseract@v2.2.1+incompatible/client.go:135 +0x50 fp=0x83ee04 sp=0x83edd0 pc=0x13a83c
command-line-arguments.cutAndRecognize(0x80c6c0, 0x3d, 0x98, 0x7a, 0xac, 0x0, 0x0, 0x0, 0x0)

goroutine 1 [chan receive]:
testing.(*T).Run(0x8ac0a0, 0x182829, 0x11, 0x18a7b0, 0x1)
	/usr/local/go/src/testing/testing.go:917 +0x2d8
testing.runTests.func1(0x8ac000)
	/usr/local/go/src/testing/testing.go:1157 +0x68
testing.tRunner(0x8ac000, 0x83df14)
	/usr/local/go/src/testing/testing.go:865 +0xa4
testing.runTests(0x80e0a0, 0x290730, 0x3, 0x3, 0x0)
	/usr/local/go/src/testing/testing.go:1155 +0x240
testing.(*M).Run(0x850100, 0x0)
	/usr/local/go/src/testing/testing.go:1072 +0x138
main.main()
	_testmain.go:46 +0x130

trap    0x0
error   0x0
oldmask 0x0
r0      0x0
r1      0x645fd2bc
r2      0x0
r3      0x8
r4      0x76f80968
r5      0x6
r6      0x645fd2bc
r7      0xaf
r8      0x76805000
r9      0x64f00044
r10     0x64f00610
fp      0x768057d4
ip      0x0
sp      0x645fd2b8
lr      0xffffffff
pc      0x766e6f24
cpsr    0x10
fault   0x0
```

# Environment

```
uname -a
Linux raspberrypi 4.19.66-v7+ #1253 SMP Thu Aug 15 11:49:46 BST 2019 armv7l GNU/Linux
```

```
go env
GOARCH="arm"
GOBIN=""
GOCACHE="/home/pi/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="arm"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/pi/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_arm"
GCCGO="gccgo"
GOARM="6"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/pi/go/src/portus/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -marm -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build900795584=/tmp/go-build -gno-record-gcc-switches"
```

```
go version
go version go1.12.9 linux/arm
```

```
tesseract --version
tesseract 5.0.0-alpha
 leptonica-1.76.0
  libgif 5.1.4 : libjpeg 6b (libjpeg-turbo 1.5.2) : libpng 1.6.36 : libtiff 4.0.10 : zlib 1.2.11 : libwebp 0.6.1 : libopenjp2 2.3.0
```

**Comment by otiai10** [comment]
@xDWart could you give me a reproducible docker?

**Comment by xDWart** [comment]
> @xDWart could you give me a reproducible docker?
I will try

**Comment by xDWart** [comment]
@otiai10 the error disappeared after reinstalling the operating system and rebuilding tesseract. Sorry for bothered you. Thank you very much for your library.
