### ISSUE TITLE
Fail in CentOS6.7 / Tesseract3.02.02 / Golang1.7.6

### ISSUE THREAD

**Issue by otiai10** [otiai10/gosseract#97]
# Reproducible Docker

```dockerfile
FROM centos:6.7

ARG TESS="3.02.02"
ARG LEPTO="v1.72"
ARG GO="1.7.6"

RUN yum update -y
RUN yum install -y yum-plugin-ovl
RUN yum install -y \
  gcc-c++ \
  wget \
  git \
  tar \
  autoconf \
  automake \
  libtool \
  libjpeg-devel \
  libpng-devel \
  libtiff-devel \
  libicu-devel \
  libpango1.0-dev \
  libcairo-dev \
  zlib-devel


ENV LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/local/lib
ENV TESSDATA_PREFIX=/usr/local/share

# Compile Leptonica
WORKDIR /
RUN mkdir -p /tmp/leptonica \
  && wget -nv https://github.com/DanBloomberg/leptonica/archive/${LEPTO}.tar.gz \
  && tar -xzf ${LEPTO}.tar.gz -C /tmp/leptonica \
  && mv /tmp/leptonica/* /leptonica
WORKDIR /leptonica

RUN mkdir m4
RUN autoreconf -i
RUN chmod a+x ./autobuild
RUN ./autobuild
RUN chmod a+x ./configure
RUN ./configure --enable-silent-rules
RUN make --silent
RUN make install --silent

# Compile Tesseract
WORKDIR /
RUN mkdir -p /tmp/tesseract \
  && wget -nv https://github.com/tesseract-ocr/tesseract/archive/${TESS}.tar.gz \
  && tar -xzf ${TESS}.tar.gz -C /tmp/tesseract \
  && mv /tmp/tesseract/* /tesseract
WORKDIR /tesseract

RUN ./autogen.sh \
  && ./configure --enable-silent-rules \
  && make 1>/dev/null \
  && make install --silent

# Load languages
RUN wget -nv https://github.com/tesseract-ocr/tessdata/raw/master/eng.traineddata -P /usr/local/share/tessdata

# Recover location
WORKDIR /

# Install Go
RUN wget -nv https://storage.googleapis.com/golang/go${GO}.linux-amd64.tar.gz \
  && tar -xzf go${GO}.linux-amd64.tar.gz
ENV GOROOT=/go

# Prepare GOPATH
RUN mkdir /gopath
ENV GOPATH=/gopath
ENV PATH=${PATH}:${GOROOT}/bin:${GOPATH}/bin

# Dependencies for tests
RUN go get github.com/otiai10/mint

# Mount source code of gosseract project
ADD . ${GOPATH}/src/github.com/otiai10/gosseract

ENTRYPOINT go test github.com/otiai10/gosseract
```

# Output

```sh
% ./test/runtime --driver docker --run CentOS6.7
┌───────────── tess3.02.02_go1.7.2_CentOS6.7
│ [Docker] Building image...
│ sha256:1d85c750b66865ce4932355c6092415ace59b29768517b2b13e4d41b512d7939
│ [Docker] Running tests...
│ actual_tessdata_num_entries_ <= TESSDATA_NUM_ENTRIES:Error:Assert failed:in file tessdatamanager.cpp, line 50
│ fatal error: unexpected signal during runtime execution
│ [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7f4566e622b0]
│
│ runtime stack:
│ runtime.throw(0x51d602, 0x2a)
│ 	/go/src/runtime/panic.go:566 +0x95
│ runtime.sigpanic()
│ 	/go/src/runtime/sigpanic_unix.go:12 +0x2cc
│
│ goroutine 7 [syscall, locked to thread]:
│ runtime.cgocall(0x4d8ab0, 0xc420023da0, 0x0)
│ 	/go/src/runtime/cgocall.go:131 +0x110 fp=0xc420023d70 sp=0xc420023d30
│ github.com/otiai10/gosseract._Cfunc_Init(0x13dc2c0, 0x0, 0x0)
│ 	github.com/otiai10/gosseract/_test/_obj_test/_cgo_gotypes.go:96 +0x45 fp=0xc420023da0 sp=0xc420023d70
│ github.com/otiai10/gosseract.(*Client).init(0xc4200561e0)
│ 	/gopath/src/github.com/otiai10/gosseract/client.go:110 +0x9f fp=0xc420023df0 sp=0xc420023da0
│ github.com/otiai10/gosseract.(*Client).Text(0xc4200561e0, 0x0, 0x0, 0x0, 0x0)
│ 	/gopath/src/github.com/otiai10/gosseract/client.go:130 +0x70 fp=0xc420023ec8 sp=0xc420023df0
│ github.com/otiai10/gosseract.TestClient_SetImage(0xc42000e600)
│ 	/gopath/src/github.com/otiai10/gosseract/all_test.go:30 +0xd0 fp=0xc420023f88 sp=0xc420023ec8
│ testing.tRunner(0xc42000e600, 0x525c78)
│ 	/go/src/testing/testing.go:610 +0x81 fp=0xc420023fb0 sp=0xc420023f88
│ runtime.goexit()
│ 	/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc420023fb8 sp=0xc420023fb0
│ created by testing.(*T).Run
│ 	/go/src/testing/testing.go:646 +0x2ec
│
│ goroutine 1 [chan receive]:
│ testing.(*T).Run(0xc42000e240, 0x518e2c, 0x13, 0x525c78, 0xc420047d01)
│ 	/go/src/testing/testing.go:647 +0x316
│ testing.RunTests.func1(0xc42000e240)
│ 	/go/src/testing/testing.go:793 +0x6d
│ testing.tRunner(0xc42000e240, 0xc420047e20)
│ 	/go/src/testing/testing.go:610 +0x81
│ testing.RunTests(0x525ca8, 0x792ea0, 0x4, 0x4, 0x566100c5)
│ 	/go/src/testing/testing.go:799 +0x319
│ testing.(*M).Run(0xc420047ee8, 0xc420047f08)
│ 	/go/src/testing/testing.go:743 +0x85
│ main.main()
│ 	github.com/otiai10/gosseract/_test/_testmain.go:66 +0xc6
│
│ goroutine 17 [syscall, locked to thread]:
│ runtime.goexit()
│ 	/go/src/runtime/asm_amd64.s:2086 +0x1
│ FAIL	github.com/otiai10/gosseract	0.008s
```

# Note

- Related: https://github.com/otiai10/gosseract/issues/59#issuecomment-348134884
- Branch: // TODO

**Comment by otiai10** [comment]
Might be helpful

- https://github.com/EddyVerbruggen/nativescript-ocr/issues/5#issuecomment-284245523
- https://stackoverflow.com/questions/41131083/tesseract-traineddata-not-working-in-swift-3-0-project-using-version-4-0
- https://github.com/tesseract-ocr/tesseract/wiki/FAQ#actual_tessdata_num_entries_-tessdata_num_entrieserrorassert-failedin-file-ccutiltessdatamanagercpp-line-55_

**Comment by otiai10** [comment]
Hey @pratty931, I figured out why you failed. The traineddata you installed are the latest one and are not compatible for tesseract 3.02. Check https://github.com/otiai10/gosseract/commit/e72539557e01bb0f433008711d6eafc495a039ff for more information and check [Dockerfile](https://github.com/otiai10/gosseract/blob/master/test/runtimes/tess3.02.02_go1.7.2_CentOS6.7.Dockerfile) for full installation example. Enjoy!
